on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: brucezcg/stm32-dev:latest
    steps:
      - name: Checkout the repository
      - uses: actions/checkout@v3
      - run: make
      - run: make cppcheck
      